- app/resources/backend/console.py
- app/resources/backend/main.py
issue #76 
Some tasks done:
1. Logging errors to console
2. Dark theme used
3. Shifted to pyqt5
console without errors
console with erros
! Currently Try/catch blocks are used only in main.py for testing purposes they need are to implemented else where in application like individual blocks,wires, utils .py files and errors can be logged from there by simply importing logger from main.py.
Some things to be handled:
1. Programs continues to run even after encountering errors.
2. Restart and Stop button for console.
> Enhancing the Console.

- frontend/src/components/blocks/package/package-widget.tsx
Fixes #142 
System | Specification
-- | --
OS | Ubuntu 20.04
Browser | Firefox 99.0
> Prevents image from being dragged on Firefox

- frontend/package-lock.json
- frontend/package.json
Changed the dependency in `package.json` to the newer `Dart sass`. 
Fixes #140 
Tests:
Runs on Ubuntu 20.04 and Firefox
> Change dependency from node-sass to sass

- backend/README.md
- docs/_pages/usermanual.md
The current backend instructions missed a step, namely the user has to run the command:
`python manage.py collectstatic`, this creates the folder from which Django serves the static files during Visual Circuit's execution.
This PR simply adds that step to instructions in both the backend `README` and the website `usermanual.md`
> Update Backend Install Instructions

- backend/synthesis/synthesis.py
Block names will have numbers appended to them to indicate which block they are.
E.g. of generated files with multiple blocks
Files generated
Implemented it using an additional dictionary to store a count of blocks
Fix #157
> Fix the naming to be unique for each block

- backend/README.md
- docs/_pages/usermanual.md
- frontend/.env.development
Using port 80 for the backend server forces the user to run the command `sudo python3 manage.py runserver` as port 80 is a reserved port by the system.
Changing to port 8000 will clear some permission issues that can occur with port 80 and allow the user the run the command without superuser privileges. 
I've also updated the instructions to reflect the new port.
> Update port used by backend from 80 to 8000

- backend/staticfiles/synthesis/lib/inputs.py
- backend/staticfiles/synthesis/lib/outputs.py
This PR will add functionality that lets the user use strings for transferring data between blocks.
Currently, the string can be submitted in two forms:
```python
data = "Hello"
outputs.share_string("Out", data)
```
```python
data = ["Hello"]
outputs.share_string("Out", data)
```
Both will work, however, if the array has more than 1 element then it will give an error
> Add read_string and share_string functions

- frontend/src/components/blocks/basic/code/code-model.ts
The basic code template currently has its main function as:
```python
def loop(...):
pass
```
I've changed it to:
```python
def main(...):
pass
```
For the new version of Visual Circuit
> Update Basic Code Template 

- backend/staticfiles/synthesis/lib/inputs.py
Key change was:
```python
if self.inputs[name].get("created", False):
number = create_ndbuffer((1,), np.float64, self.inputs[name]["data"].buf)
self.inputs[name]["data"] = data_wire # Stores the SHM Object in "data"
```
This enables us to get the output properly:
Fix #164
> Fix read_number function 

- backend/staticfiles/synthesis/lib/inputs.py
- backend/staticfiles/synthesis/lib/outputs.py
- backend/staticfiles/synthesis/main.py
This PR creates functions which will allow users to share any type of data using simple `share()` and `read()` functions as opposed to separate functions like `read_string()`, `share_string()`, `read_number()` etc.
This has been tested with images, numbers and strings on Linux.
> Add functions to share any type of data

- backend/synthesis/synthesis.py
Currently, the built application doesn't have the .vc3 file of the project. Hence, it is difficult to edit the project structure on Visual Circuit unless you have a copy.
This PR will build the `.vc3` file along with the application when the user presses 'Build and Download'
> Add the .vc3 file to the built application

- frontend/src/components/blocks/basic/code/code-widget.tsx
- frontend/src/components/blocks/basic/constant/constant-widget.tsx
- frontend/src/components/utils/tooltip/index.tsx
1. Implemented the addition of three units: k or K, m, M (representing Thousands, milli, Mega) to facilitate seamless conversion for both constant input and internal code block.
2. Also, added the internal code block frequency section to accept units. If the value is a decimal and close to 0, it will be set to 0 (e.g., 4m).
3. In the Cropper and various other blocks, multiple parameters are included within a single constant. To address this, each value is now separated by commas. Subsequently, the necessary conversions are applied, followed by the reintroduction of commas. This ensures the internal code functions smoothly without encountering any issues.
Fixes: #271
(Used all values for example purpose)
Canvas area - Cropper internal block with xywh of 5.73k,0.0012m,12M,248 and frequency …
> Added unit conversion feature in constants block and internal code frequency input

- frontend/src/components/blocks/basic/constant/constant-widget.tsx
- frontend/src/components/blocks/basic/input/input-widget.tsx
- frontend/src/components/blocks/basic/output/output-widget.tsx
1. There are three blocks which has rename functionality ( constant, input and output ), implemented keydown event handler to detect the Alt+R or Alt+r key combination when particular block is selected.
2. Ensured that the shortcut key functionality only works when the lock on internal blocks containing constant, input, or output is opened, preventing any unintended changes to internal blocks with locks.
Fixes: #282 
When the lock on an internal block is open, pressing Alt+R opens a dialog box for renaming - Screenshot
In the main canvas, after pressing the shortcut key for renaming- Screenshot
> Added Alt+R and Alt+r as shortcut key for Renaming of blocks

- .github/workflows/CI_Workflow.yml
- frontend/src/App.test.tsx
1. Added a YAML file that triggers the installation job and performs basic frontend tests whenever a new pull request is made to the master branch.
2. Wrote the script according to the installation process outlined in the new Visual Circuit documentation.
3. Implemented action cache for node modules and artifacts for the Python virtual environment to reduce installation time.
4. In the frontend test, it verifies the presence of the text "File" in the menubar of the VisualCircuit application rendered in App.tsx.
CI Workflow tested in forked repo:
> Added CI Workflow with basic frontend test

- backend/synthesis/synthesis.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/blocks/common/base-port/index.tsx
- frontend/src/components/blocks/common/factory.tsx
- frontend/src/components/blocks/package/package-model.ts
- frontend/src/components/dialogs/blocks-dialog.tsx
- frontend/src/components/menu/index.tsx
- frontend/src/core/constants.ts
- frontend/src/core/editor.ts
- frontend/src/core/serialiser/converter.ts
- frontend/src/core/serialiser/interfaces.ts
- frontend/yarn.lock
- Composed Block Feature
1. Added an option in the menu bar for building the composed block.
2. After clicking the composed block option, a dialog box appears from which all available global inputs and outputs can be selected.
3. After selecting the global inputs and outputs, the .vc3 file is generated and saved in the downloads folder with the respective global input and output links.
4. The composed block also supports nested blocks in the .vc3 file.
- Nested issue
1. Added nested processing on the backend.
2. Modified the existing single code block dependency code to support multi-level dependencies with multiple code blocks.
3. All nested and zero-level block Python scripts are placed in the modules directory.
4. Added processing for wires, including filtering and mapping to the …
> Composed block feature with solved nested issue

- backend/synthesis/synthesis.py
1. The main issue was in the backend processing, specifically in the synthesis.py file within the synthesis_module function, so I modified it to fix the problem.
2. Restructured the overall process_wire function to properly store and map multiple wires. The wire_check_source and wire_check_target dictionaries now store intermediate wires by checking the wire ports (i.e., input-out, output-in).
3. After refining the valid_wires, the wires are checked against blocks with global ports. Based on the source and target, wires are connected. If multiple wires are present, another iteration connects all new wires to the relevant port.
4. Removed duplicate wires using a set. This process continues until all wires are mapped correctly.
Fixes: #338 …
> Fixed the issue of missing wires when multiple blocks are connected to other multiple blocks through a single block (port)

- frontend/src/core/editor.ts
Changes:
The labels are changed to show just a name, instead of 'block......'. The package blocks show only the name and not the type 'block.package'
> fix: show only meaningful names for blocks in global input popup

- frontend/src/components/menu/index.tsx
- frontend/src/core/editor.ts
Issue:
When no project name is present, the saved block name is empty, which makes it confusing when using it later on.
Fix:
When no project name / block name is present we use the filename from which it is loaded as the default name.
> feat: use the file name as default when project name is empty

- frontend/src/core/editor.ts
Issue:
The project info is retained when we use File > New to start a new circuit.
So, this PR fixes it by clearing the info.
> fix: clear the project info object

- README.md
- VC+/README.md
- backend/README.md
Fixes #363 
The documentation previously used relative paths for links, which caused issues. I updated the links to use absolute paths to ensure they work correctly and are no longer broken.
> Updated documentation links to use absolute paths
